-- =====================================================
-- Koppal Ganapathi Utsava 2026 — Seed Data
-- No dummy mandals — mandals are created dynamically
-- when users submit their evaluations.
-- =====================================================

-- =====================================================
-- ADMIN USER SETUP
-- After running this seed, create an admin user:
--
-- 1. Sign up through the app or create a user in
--    Supabase Dashboard > Authentication > Users
--
-- 2. Then run this SQL to make them admin:
--    UPDATE public.profiles
--    SET is_admin = TRUE
--    WHERE email = 'your-admin-email@example.com';
--
-- =====================================================
